### ISSUE TITLE
Checkpoint request

### ISSUE THREAD

**Issue by WHlTE-N0lSE** [alexandrosstergiou/progressive-action-prediction#2]
I encountered some difficulties in the process of reproducing your work, would you like to share the pre-trained checkpoint? thank you very much!

**Comment by ToanLyHoa** [comment]
> I encountered some difficulties in the process of reproducing your work, would you like to share the pre-trained checkpoint? thank you very much!

Did you completely reproduce his work, I try to train but it seems not to get high accuracy as possible. Tell me if you did handled it. Thank you so much.

**Comment by ya-92626** [comment]
> > I encountered some difficulties in the process of reproducing your work, would you like to share the pre-trained checkpoint? thank you very much!
> 
> Did you completely reproduce his work, I try to train but it seems not to get high accuracy as possible. Tell me if you did handled it. Thank you so much.

Hello, I would like to ask you some questions. In the part of video data processing, I use UCF-101 data set. How should I use the script
A custom format is used for the train/val label files of each datasets:

label	youtube_id/id	time_start(optional)	time_end(optional)	split
This can be done through the scripts provided in labels

**Comment by aonihao1** [comment]
> > I encountered some difficulties in the process of reproducing your work, would you like to share the pre-trained checkpoint? thank you very much!
> 
> Did you completely reproduce his work, I try to train but it seems not to get high accuracy as possible. Tell me if you did handled it. Thank you so much.

Hello, I would like to ask you some questions. In the part of video data processing, I use UCF-101 data set, how to use the script? I didn't understand the official information.The part I don't know how to manipulate is here:
A custom format is used for the train/val label files of each datasets:

This can be done through the scripts provided in labels
We have tested our code over the following datasets:
Conversion of videos to SQLite3
Instead of extracting video frames stored as image files (//etc.) that dramatically increase the number of inodes use, we use files for each video and store frames as BLOBS..png.jpeg.db
You can use the pypi [package](https://pypi.org/project/dataset2database/) or [repo](https://github.com/alexandrosstergiou/dataset2database) to convert video files to SQL:dataset2databse
..............................................................................................................................................................................................................................
I don't know much about the code, and I really hope to get your help. I really appreciate it，Looking forward to your reply! If possible, I hope to have your contact information, wechat or ins, etc

**Comment by ToanLyHoa** [comment]
> > > I encountered some difficulties in the process of reproducing your work, would you like to share the pre-trained checkpoint? thank you very much!
> > 
> > 
> > Did you completely reproduce his work, I try to train but it seems not to get high accuracy as possible. Tell me if you did handled it. Thank you so much.
> 
> Hello, I would like to ask you some questions. In the part of video data processing, I use UCF-101 data set, how to use the script? I didn't understand the official information.The part I don't know how to manipulate is here: A custom format is used for the train/val label files of each datasets:
> 
> This can be done through the scripts provided in labels We have tested our code over the following datasets: Conversion of videos to SQLite3 Instead of extracting video frames stored as image files (//etc.) that dramatically increase the number of inodes use, we use files for each video and store frames as BLOBS..png.jpeg.db You can use the pypi [package](https://pypi.org/project/dataset2database/) or [repo](https://github.com/alexandrosstergiou/dataset2database) to convert video files to SQL:dataset2databse .............................................................................................................................................................................................................................. I don't know much about the code, and I really hope to get your help. I really appreciate it，Looking forward to your reply! If possible, I hope to have your contact information, wechat or ins, etc

My ins: th__mih, pm for me and I will answer your question

**Comment by alexandrosstergiou** [comment]
Hi both, checkpoints for UCF-101 and SSsub-21 are available with the latest commit.
